name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: |
        for t in autogen.sh configure
        do sh "$t"
        done
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
      continue-on-error: true
    - name: upload test log
      uses: actions/upload-artifact@v2.2.3
      with:
        name: test-log
        path: fakechroot-2.20.2/_build/sub/test/test-suite.log
